/*
 * This source file was generated by the Gradle 'init' task
 */
package vs.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void applicationCanStart() {
        // Test that the Application class can be instantiated
        Application application = new Application();
        assertNotNull(application, "Application should be instantiable");
    }
}
